### ISSUE TITLE
lots of API calls

### ISSUE THREAD

**Issue by arrested-developer** [fac-14/Week4TakingAIME#59]
A new API call is triggered every time a key is pressed, so if a few keys are typed in rapid succession, 
the server has to respond to multiple API calls, and all but the final one are basically ignored in the client.

Could your JS wait until the user has finished typing before sending the XHR request?

(We found a way to deal with this if you'd like to chat solutions ⛑ )

**Comment by sbinlondon** [comment]
@sima-qian @EmilyScripts @MissArray This might be useful to have the debounce function I was talking about

**Comment by sima-qian** [comment]
@arrested-developer saw your solution -- great idea 👍
